### ISSUE TITLE
Fails to decode some EHS message

### ISSUE THREAD

**Issue by yanghsu** [openskynetwork/java-adsb#17]
There is a message makes the example decoder crash. 

    $ java -cp libadsb-2.1.jar org.opensky.example.ExampleDecoder 
    1,abd30f589bc61c
    Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
        at org.opensky.libadsb.msgs.CommBIdentifyReply.<init>(CommBIdentifyReply.java:73)
        at org.opensky.libadsb.Decoder.genericDecoder(Decoder.java:108)
        at org.opensky.example.ExampleDecoder.decodeMsg(ExampleDecoder.java:78)
        at org.opensky.example.ExampleDecoder.main(ExampleDecoder.java:284)

message is “abd30f589bc61c”

What's wrong with this message or the decoder?

**Comment by mablae** [comment]
I will try to debug it with the python decoder wich is a bit more solid.

**Comment by yanghsu** [comment]
I have reviewed the python decoder. It seems like an EHS message should be 28 byte hex chars.
I am not sure about it.

**Comment by affitz** [comment]
The reason for this error was that the raw message you fed into the receiver has downlink format 21 and a length of 7 bytes. DF 21 is supposed to have a length of 14 bytes according to the standards. The decoder now behaves like this:

java -cp libadsb-2.1.jar org.opensky.example.ExampleDecoder 
1,abd30f589bc61c
Malformed message! Skipping it. Message: Message 'abd30f589bc61c' has an illegal format: Downlink format 21 suggests length 14 byte but input has length 7

Fixed in 765b65c
